#!/bin/bash
set -e # Stop script executing on any error code

# Add Backports distro
########################################################################################################################
echo "deb http://deb.debian.org/debian bullseye-backports main" > /etc/apt/sources.list.d/bullseye-backports.list

# Update Packages and Distro
########################################################################################################################
apt update && apt upgrade -y && apt dist-upgrade -y

# Install missing software
########################################################################################################################
apt install zsh git/bullseye-backports -y

# Install zsh plugins
########################################################################################################################
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Install oh-my-zsh
########################################################################################################################
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"